""""""""""""
" Behaviour

" Incompatible with vi
set nocompatible

" encoding
set encoding=utf8
scriptencoding utf-8

"""""""""""""""""
" Editor settings

" indentation
set ignorecase
set smartcase
set incsearch

" EOL settings
set ffs=unix,dos,mac

" no backups
set nobackup
set nowb
set noswapfile
set viminfo=

" allow modified/unsaved buffers
set hid

" hide buffers instead of deleting them
set bufhidden=hide

" enable mouse support
set mouse=a

" show line numbers
set number

" reduce Esc keycode delay
set ttimeoutlen=50

" backspace and cursor keys wrap to previous/next line
set backspace=indent,eol,start whichwrap+=<,>,[,]

" disable auto insertion of comments
autocmd BufEnter * set formatoptions-=cro

" disable annoying formatting for html (help html.vim)
let html_no_rendering=1

" disable searching in include files for autocomplete
set complete-=i

" maintain the current column after various commands
set nostartofline

" default split locations - impacts help placement
set splitbelow
set splitright

" keep some rows/columns visible when moving cursor at the edges of the screen
set scrolloff=3
set sidescrolloff=3

""""""""""""""
" UI settings 

if has("gui_running")
  " remove menu bar
  set guioptions-=m
  " remove toolbar
  set guioptions-=T
  " remove left scroll bar
  set guioptions+=Ll
  set guioptions-=Ll

  if has("X11")
    set guifont=Monospace\ 12,Consolas\ 11,Courier\ New\ 10
  elseif has("gui_macvim")
    set guifont=Fira\ Mono\ for\ Powerline:h16
  elseif has("win32")
    set renderoptions=type:directx
    set guifont=RobotoMono_Nerd_Font_Mono:h11,Consolas:h11,Courier_New:h10
  endif

  set lines=40
  set columns=130

  " foldcolumn is 3 characters wide
  set foldcolumn=3
endif

" highlight with gui colors when running in the terminal
if v:version > 800
  set termguicolors
endif

" fill vertical bar with dots
set fillchars+=vert:.

" enable completion menu
set wildmenu

" always show cursor position
set ruler

" monocolor in terminal
let g:terminal_ansi_colors = ['white', 'white', 'white', 'white', 'white', 'white', 'white', 'white',
                            \ 'white', 'white', 'white', 'white', 'white', 'white', 'white', 'white']

"""""""""""""""
" Key mappings

" setup leader
let mapleader = ","
let g:mapleader = ","
let maplocalleader = ","

if has("clipboard")
  vmap <C-x> "+x
  smap <C-x> <C-g>"+x
  nmap <silent> <C-X> :call CutNonEmptyLineToClipboard()<CR>
else
  vmap <C-x> "cx
  smap <C-x> <C-g>"cx
  nmap <silent> <C-X> :call CutNonEmptyLineToCReg()<CR>
endif

" If the current line is non-empty cut it to the clipboard
" An empty line is put into the black hole registry
function! CutNonEmptyLineToClipboard()
    if match(getline('.'), '^\s*$') == -1
        normal 0"+d$
    else
        normal "_dd
    endif
endfunction

function! CutNonEmptyLineToCReg()
    if match(getline('.'), '^\s*$') == -1
        normal 0"cd$
    else
        normal "_dd
    endif
endfunction

if has("clipboard")
  " CTRL-C is Copy
  vmap <C-C> "+y

  " CTRL-V is Paste
  map <C-V>	"+gP

  " enable Paste in command mode
  cmap <C-v> <C-R>+

  exe 'inoremap <script> <C-V>' paste#paste_cmd['i']
  exe 'vnoremap <script> <C-V>' paste#paste_cmd['v']
else
  " clipboard unavailable, use c registry
  vmap <C-C> "cy
  map <C-V>	"cgP
  cmap <C-v> <C-R>c
endif

" Enable yanked text to be pasted multiple times
xnoremap p pgvy

" Use CTRL-Q to do what CTRL-V used to do
noremap <C-Q> <C-V>

" CTRL-C to copy text from cmd line
cnoremap <C-c> <C-y>

" better movement in command line
if has("gui_running")
  cnoremap <C-H> <Left>
  cnoremap <C-L> <Right>
  cnoremap <C-A> <Home>
  cnoremap <C-E> <End>
endif

" remap : in select mode, which normally inserts text
smap : <Esc>:

if has("clipboard")
  noremap <leader>ff :let @+=expand("%:p")<CR>
  noremap <leader>fn :let @+=expand("%:t")<CR>
  noremap <leader>fd :let @+=expand("%:p:h")<CR>
else
  noremap <leader>ff :let @c=expand("%:p") \| call TmuxCopyReg("c")<CR>
  noremap <leader>fn :let @c=expand("%:t") \| call TmuxCopyReg("c")<CR>
  noremap <leader>fd :let @c=expand("%:p:h") \| call TmuxCopyReg("c")<CR>
endif

function! TmuxCopyReg(r)
  if $TMUX == ''
        return
    endif
  call system('tmux loadb -w -', getreg(a:r))
endfunc

if has("win32")
  map <leader>e :silent r! explorer .<CR>
end

nmap <leader>z :let &scrolloff=999-&scrolloff<CR>

" awesome keyboard scrolling
nmap <C-j> 3j3<C-e>
nmap <C-k> 3k3<C-y>

" change current dir
nmap <leader>cd :cd\ %:p:h<CR>

""""""""""""""
" Indentation

set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smarttab

set autoindent

" long lines don't break at screen end
set nowrap

" long lines are market with > and < at end of screen
set listchars+=precedes:<,extends:>

""""""""""""""
" Status line

set laststatus=2
set statusline=
set statusline+=%1*                   " switch to User1 highlight
set statusline+=%n                    " buffer number
set statusline+=%1*
set statusline+=%{'/'.bufnr('$')}\    " total buffers
set statusline+=%2*
set statusline+=%<%1.200F              " filename
set statusline+=%3*
set statusline+=\ %y%h%w              " filetype, help, example flags
set statusline+=%3*
set statusline+=%r%m                  " read-only, modified flags
set statusline+=%3*
set statusline+=%=\                   " indent right
set statusline+=%1*
set statusline+=%l                    " line number
set statusline+=%1*
set statusline+=/%{line('$')}         " total lines
set statusline+=%1*
set statusline+=,                     " ,
set statusline+=%1*
set statusline+=%c%V                  " [virtual] column numberV
set statusline+=%3*
set statusline+=\                     " [ ]
set statusline+=%3*
set statusline+=%<%P                  " percent

""""""""""""""""""
" Custom commands

" show highlight group
command! Hgroup :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . "> "
                  \ . "trans<". synIDattr(synID(line("."),col("."),0),"name") . "> "
                  \ . "lo<". synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"

" find text in all open buffers
function! Findb(text)
    exe "cex [] | silent! bufdo vimgrepa /" . a:text . "/ %"
    :copen
endfunction
command! -nargs=1 Findo call Findo(<q-args>)

function! ReturnHighlightTerm(group, term)
  let output = execute('hi ' . a:group)
  return matchstr(output, a:term.'=\zs\S*\>')
endfunction

" toggle transparency
let s:hiBgData = { 'on': 0 }
function! Transparent()
  if !s:hiBgData.on
    let s:hiBgData.Normal = ReturnHighlightTerm('Normal', 'guibg')
    let s:hiBgData.NonText = ReturnHighlightTerm('NonText', 'guibg')
    let s:hiBgData.SignColumn = ReturnHighlightTerm('SignColumn', 'guibg')
    let s:hiBgData.FoldColumn = ReturnHighlightTerm('FoldColumn', 'guibg')
    let s:hiBgData.LineNr = ReturnHighlightTerm('LineNr', 'guibg')
    exe 'hi Normal guibg=NONE'
    exe 'hi NonText guibg=NONE'
    exe 'hi SignColumn guibg=NONE'
    exe 'hi FoldColumn guibg=NONE'
    exe 'hi LineNr guibg=NONE'
    let s:hiBgData.on = 1
  else
    if len(s:hiBgData.Normal) > 0 | exe 'hi Normal guibg=' . s:hiBgData.Normal | endif
    if (len(s:hiBgData.NonText) > 0) | exe 'hi NonText guibg=' . s:hiBgData.NonText | endif
    if (len(s:hiBgData.SignColumn) > 0) | exe 'hi SignColumn guibg=' . s:hiBgData.SignColumn | endif
    if (len(s:hiBgData.FoldColumn) > 0) | exe 'hi FoldColumn guibg=' . s:hiBgData.FoldColumn | endif
    if (len(s:hiBgData.Number) > 0) | exe 'hi LineNr guibg=' . s:hiBgData.Number | endif
    let s:hiBgData.on = 0
  endif
endfunc
command! Transparent call Transparent()

"""""""""""""""""""""
" File type settings

autocmd FileType markdown setlocal tabstop=4|set shiftwidth=4|set expandtab
highlight link markdownError Normal
autocmd FileType vim setlocal iskeyword-=#
autocmd FileType * setlocal iskeyword-=:
autocmd FileType css,scss,html,eruby setlocal iskeyword +=-

""""""""""
" Plugins

" Pathogen is still needed for older versions of vim
execute pathogen#infect()

let g:BufstopAutoSpeedToggle = 1

let g:terminal_drawer_leader = '<C-\>'
let g:terminal_drawer_shell = '++kill=hup'

let g:vimspector_enable_mappings = 'HUMAN'

let g:vim_tmux_clipboard#loadb_option = '-w'

let g:tmux_navigator_no_mappings = 1

call plug#begin('~/.vimdata')

Plug 'mihaifm/bufstop'
Plug 'mihaifm/vimpanel'
Plug 'mihaifm/4colors', { 'do': ':colorscheme 4colors' }
Plug 'easymotion/vim-easymotion'
Plug 'itchyny/lightline.vim'
Plug 'puremourning/vimspector'
Plug 'roxma/vim-tmux-clipboard'
Plug 'christoomey/vim-tmux-navigator'
Plug 'iaalm/terminal-drawer.vim'
Plug 'mbbill/undotree'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()

colorscheme 4colors

filetype plugin indent on
syntax on

"""""""""""""""
" Legacy stuff

if &term == "dtterm"
  set t_KD=^<Delete>
  fixdel
endif

set secure
