---@diagnostic disable-next-line
local logo1 = [[
 ███▄    █ ▓█████  ▒█████   ██▒   █▓ ██▓ ███▄ ▄███▓   
 ██ ▀█   █ ▓█   ▀ ▒██▒  ██▒▓██░   █▒▓██▒▓██▒▀█▀ ██▒   
▓██  ▀█ ██▒▒███   ▒██░  ██▒ ▓██  █▒░▒██▒▓██    ▓██░   
▓██▒  ▐▌██▒▒▓█  ▄ ▒██   ██░  ▒██ █░░░██░▒██    ▒██    
▒██░   ▓██░░▒████▒░ ████▓▒░   ▒▀██  ░██░▒██▒   ░██▒   
░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒░▒░▒░    ░ ▐░  ░▓  ░ ▒░   ░      
░ ░░   ░ ▒░ ░ ░  ░  ░ ▒ ▒░    ░ ░░   ▒ ░░  ░      ░   
   ░   ░ ░    ░   ░ ░ ░ ▒       ░░   ▒ ░░      ░      
         ░    ░  ░    ░ ░        ░   ░         ░      
                                  ░                   
]]

---@diagnostic disable-next-line
local logo2 = [[
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXXQQQQXXQQXXXXXXQQQXXXXXQQQXXQQQQQQQXXQXXQQXXXQQQXXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXXXQQQXXQQXXQQQQQQXXQQQXXQQQXXQQQQQXXQQXXQQXXXXQXXXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXQXXQQXXQQXXXXQQQXXQQQQQXXQQQXXQQQXXQQQXXQQXXQXXXQXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXQQXXQXXQQXXQQQQQXXQQQQQXXQQQQXXQXXQQQQXXQQXXQQXQQXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXQQQXXXXQQXXQQQQQQXXQQQXXQQQQQQXXXQQQQQXXQQXXQQQQQXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQXXQQQQXXXQQXXXXXXQQQXXXXXQQQQQQQQXQQQQQQXXQQXXQQQQQXXQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQMIHAIFM
]]

local function randomUppercase()
    local char
    repeat
        char = string.char(math.random(65, 90))
    until char ~= 'Q'
    return char
end

local function replaceWithRandomUppercase(str)
  local result = ""
  for i = 1, #str do
    local char = str:sub(i, i)
    if char:match("Q") then
      result = result .. randomUppercase()
    elseif char:match("X") then
      result = result .. " "
    else
      result = result .. char
    end
  end
  return result
end

logo2 = replaceWithRandomUppercase(logo2)

---@diagnostic disable-next-line
local logo3 = [[
SJFEVPWBCUPDWXJHFIMRTWHPPKUYBSCBITUWSGVJLCOZSKNINMOADYAHCECFOAVNSYLGXMZKZFPUZJJKPNVUIHRDWFVUFXTGVFPYKSORHHRJNUUYFWWPJTFXBAALYMMRGOEBX
GZKKRZPCAZMPMYLPZPMDPKSTXXDISVAERZNZYMHV/  VWGO \VW     \CVH     ZDN  \UCFJN/  M  MU/  VDF  \AFBUUWDMZYKWZWPVWJVZGKCHWOPWBJVSRROLGHCF
WGILLXBNSVLITRKGXCMNZFSOBFYJVWUDTLKJRFJE    \SU  GV  ZHTVMR .KXM. HKF  YSIRG  ZK/\NP    G    EZDRTZKBNETUNZBFFXEHNBPPBBYBICUFPAYNJXJJ
BNCFOMACLFAZBVZOXXNTOCGDYLLFSHRSIYMCPWSX  A  \I  ET    RKI  MESPU  KUE  LPI  JOH  GU  H   X  OJZHMLGUEZZADUNGWYLWMZCPTPYXMYFFBYEAWKTN
KTYTJLRNNFEYSDIYXOKZYZVMCDOKKGPRMISOAMUL  DP  \  YK  MKFVZ  RIJBF  ZCUA  V  XITG  IS  J\V/J  BCJYJUMGEOSHGLJPDLGFWWFSDFPNEPOGKGFUDPSN
IXPJNBFAVGVYZDNLEYHKBXICGGIFEWVBHTWBLCNV  EZI   /LB  UCZIST .GUH. DBDZDA   TREYU  JR  ENZZP  JVEDAGABCINBZIAVXOHFNGDTVWRCUKZOIXYILUNC
BEUTDOZPFEWZALTFFEPEGEXVXYTUWLTJPYLKHGIK\ LVZX_/AAH_,_,_/AMR,   /TWYXJEU\ /WGMTN  UR\ XUEFD /OCHPVEETKAOPXVKPCZFRAZLSRGRAVHFUJWJHCCOL
BJVPIDXBGASPXWIJOTXUXLEDDTMBTRBPYFAVKCESCLYYHTLFLWPVJAUYYDLYSKEKECCRVOZZGTAHRNEVOZWDJDVSGYRKOYFRTPEVKJDROYCMGRPPJDSUPDELIMDWMEMIHAIFM
]]

return logo2
