---
- name: Trixie VM config
  hosts: debian_vms
  become: true
  gather_facts: true

  vars:
    dev_user: debian

    base_packages:
      - ca-certificates
      - curl
      - git
      - gnupg
      - unzip
      - xz-utils
      - fuse
      - unzip
      - fontconfig

    dev_packages:
      - tmux
      - fzf
      - ripgrep
      - nodejs
      - npm
      - firefox-esr
      - kitty

    desktop_packages:
      - spice-vdagent
      - xserver-xorg-video-qxl
      - xserver-xorg-input-libinput
      - xinput
      - xfce4
      - xfce4-goodies
      - dbus-x11
      - xrdp
      - xorgxrdp
      - arc-theme
      - papirus-icon-theme

    nerd_fonts:
      - JetBrainsMono
      - FiraCode
      - CascadiaCode

    marker_dir: "/etc/markers"

    nvim_install_path: "/opt/nvim/nvim"

    gh_keyring_path: "/etc/apt/keyrings/githubcli-archive-keyring.gpg"
    gh_repo: "deb [arch={{ ansible_architecture | replace('x86_64','amd64') }} signed-by={{ gh_keyring_path }}] https://cli.github.com/packages stable main"

    xfce_gtk_theme: Arc-Dark
    xfce_icon_theme: Papirus-Dark

    nerd_fonts_version: "v3.4.0"
    nerd_fonts_dir: /usr/local/share/fonts/NerdFonts
    nerd_fonts_marker: "{{ marker_dir }}/nerd_fonts_installed"

  handlers:
    - name: Restart xrdp
      ansible.builtin.service:
        name: xrdp
        state: restarted

  tasks:

    ###################
    # Install packages

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ base_packages }}"
        state: present

    - name: Install developer packages
      ansible.builtin.apt:
        name: "{{ dev_packages }}"
        state: present

    - name: Install desktop + RDP packages
      ansible.builtin.apt:
        name: "{{ desktop_packages }}"
        state: present

    ################
    # System tweaks

    - name: Ensure marker directory exists
      ansible.builtin.file:
        path: "{{ marker_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure virtio_input module is loaded now
      ansible.builtin.modprobe:
        name: virtio_input
        state: present

    - name: Persist virtio_input module across reboots
      ansible.builtin.copy:
        dest: /etc/modules-load.d/virtio-input.conf
        mode: "0644"
        content: "virtio_input\n"

    - name: Restart LightDM
      ansible.builtin.systemd:
        name: lightdm
        state: restarted

    ##################
    # Neovim AppImage

    - name: Ensure Neovim install dir exists
      ansible.builtin.file:
        path: "/opt/nvim"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Download/update Neovim AppImage (latest)
      ansible.builtin.get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage"
        dest: "{{ nvim_install_path }}"
        mode: "0755"
      register: nvim_dl

    - name: Symlink nvim into PATH
      ansible.builtin.file:
        src: "{{ nvim_install_path }}"
        dest: "/usr/local/bin/nvim"
        state: link
        force: true

    #############
    # GitHub CLI 

    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install GitHub CLI keyring
      ansible.builtin.get_url:
        url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
        dest: "{{ gh_keyring_path }}"
        mode: "0644"

    - name: Add GitHub CLI apt repository
      ansible.builtin.apt_repository:
        repo: "{{ gh_repo }}"
        filename: "github-cli"
        state: present
        update_cache: true

    - name: Install GitHub CLI
      ansible.builtin.apt:
        name: gh
        state: present

    ###################
    # OpenAI Codex CLI

    - name: Ensure npm global installs go to /usr/local (safe default)
      ansible.builtin.command: "npm config set prefix /usr/local"
      changed_when: false

    - name: Install/Update OpenAI Codex CLI
      ansible.builtin.command: "npm install -g @openai/codex"
      args:
        creates: "/usr/local/bin/codex"

    ##############
    # Claude Code

    - name: Download Claude install script
      get_url:
        url: https://claude.ai/install.sh
        dest: /tmp/claude-install.sh
        mode: '0755'

    - name: Run Claude Code install script
      become: false
      become_user: "{{ dev_user }}"
      shell: bash /tmp/claude-install.sh
      args:
        creates: "/home/{{ dev_user }}/.local/bin/claude"

    - name: Add ~/.local/bin to PATH in .bashrc
      become: false
      become_user: "{{ dev_user }}"
      lineinfile:
        path: "/home/{{ dev_user }}/.bashrc"
        line: 'export PATH="$HOME/.local/bin:$PATH"'
        state: present

    #############
    # Nerd Fonts

    - name: Create Nerd Fonts directory
      file:
        path: "{{ nerd_fonts_dir }}"
        state: directory
        mode: '0755'

    - name: Check if fonts already installed
      stat:
        path: "{{ nerd_fonts_marker }}"
      register: nerd_fonts_installed

    - name: Download Nerd Fonts archives
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_version }}/{{ item }}.zip"
        dest: "/tmp/{{ item }}.zip"
        mode: '0644'
      loop: "{{ nerd_fonts }}"
      when: not nerd_fonts_installed.stat.exists

    - name: Unzip Nerd Fonts
      unarchive:
        src: "/tmp/{{ item }}.zip"
        dest: "{{ nerd_fonts_dir }}"
        remote_src: true
      loop: "{{ nerd_fonts }}"
      when: not nerd_fonts_installed.stat.exists

    - name: Remove downloaded archives
      file:
        path: "/tmp/{{ item }}.zip"
        state: absent
      loop: "{{ nerd_fonts }}"
      when: not nerd_fonts_installed.stat.exists

    - name: Rebuild font cache
      command: fc-cache -f
      when: not nerd_fonts_installed.stat.exists

    - name: Create install marker
      file:
        path: "{{ nerd_fonts_marker }}"
        state: touch
      when: not nerd_fonts_installed.stat.exists

    #######
    # XRDP

    - name: Ensure debian user has a password for RDP
      ansible.builtin.user:
        name: debian
        # password generated with: openssl passwd -6
        password: "$6$xpeyN4Bt9sBZFl73$7HqO4FvmkmIR98LkXlJDY6ONu.8zHYNkJEi6bOIRzUZq0P.Tg9XXFflSIT8woQoFEGyoExJwOAFEkTGECCfzA."

    - name: Ensure xrdp is enabled and started
      ansible.builtin.service:
        name: xrdp
        enabled: true
        state: started

    - name: Add xrdp user to ssl-cert group
      ansible.builtin.user:
        name: xrdp
        groups: ssl-cert
        append: true
      notify: Restart xrdp

    - name: Allow Xorg for non-console users (needed for XRDP)
      ansible.builtin.copy:
        dest: /etc/X11/Xwrapper.config
        content: |
          allowed_users=anybody
          needs_root_rights=yes
        owner: root
        group: root
        mode: "0644"
      notify: Restart xrdp

    - name: Configure XRDP to start XFCE
      ansible.builtin.copy:
        dest: /etc/xrdp/startwm.sh
        content: |
          #!/bin/sh
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR
          exec startxfce4
        owner: root
        group: root
        mode: "0755"
      notify: Restart xrdp

    ########
    # SPICE

    - name: Ensure spice-vdagentd socket is enabled and started
      ansible.builtin.systemd:
        name: spice-vdagentd.socket
        enabled: true
        state: started

    - name: Ensure spice-vdagentd service is enabled and started
      ansible.builtin.systemd:
        name: spice-vdagentd.service
        enabled: true
        state: started

    - name: Ensure SPICE vdagent autostarts for all desktop sessions
      ansible.builtin.copy:
        dest: /etc/xdg/autostart/spice-vdagent.desktop
        mode: "0644"
        content: |
          [Desktop Entry]
          Type=Application
          Name=Spice vdagent
          Exec=/usr/bin/spice-vdagent
          NoDisplay=true
          X-GNOME-Autostart-enabled=true

    ########################
    # Destkop customization

    - name: Ensure per-user xfconf directory exists
      ansible.builtin.file:
        path: "/home/{{ dev_user }}/.config/xfce4/xfconf/xfce-perchannel-xml"
        state: directory
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: "0755"

    - name: Set Xfce theme + icons
      ansible.builtin.copy:
        dest: "/home/{{ dev_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml"
        owner: "{{ dev_user }}"
        group: "{{ dev_user }}"
        mode: "0644"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>

          <channel name="xsettings" version="1.0">
          <property name="Net" type="empty">
          <property name="ThemeName" type="string" value="{{ xfce_gtk_theme }}"/>
          <property name="IconThemeName" type="string" value="{{ xfce_icon_theme }}"/>
          </property>
          </channel>

    - name: Set kitty as default x-terminal-emulator
      ansible.builtin.alternatives:
        name: x-terminal-emulator
        path: /usr/bin/kitty
